### ISSUE TITLE
Matrix can not be modified

### ISSUE THREAD

**Issue by zhengfuwang** [RuffianZhong/RWidgetHelper#40]
这个问题在 4.4.* 版本必现

**崩溃日志**

````
09-17 14:27:22.690 10498-10498/com.ruffian.library.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ruffian.library.demo, PID: 10498
    java.lang.IllegalStateException: Matrix can not be modified
        at android.graphics.Matrix$1.oops(Matrix.java:40)
        at android.graphics.Matrix$1.setRectToRect(Matrix.java:202)
        at com.ruffian.library.widget.helper.RImageViewHelper.drawBitmapSrc(RImageViewHelper.java:308)
        at com.ruffian.library.widget.helper.RImageViewHelper.drawBitmap(RImageViewHelper.java:243)
        at com.ruffian.library.widget.helper.RImageViewHelper.onDraw(RImageViewHelper.java:209)
        at com.ruffian.library.widget.RImageView.onDraw(RImageView.java:34)
        at android.view.View.draw(View.java:14739)
        at android.view.View.getDisplayList(View.java:13599)
        at android.view.View.getDisplayList(View.java:13646)
````

**崩溃机型**
![20190917143750.png](https://i.loli.net/2019/09/17/zb1Ywj56MtqCBl2.png)

**解决方案**
https://stackoverflow.com/a/25381660
```
Matrix matrix;
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
    matrix = mView.getMatrix();
} else {
    matrix = new Matrix();
    matrix.set(mView.getMatrix());
}
```

**Comment by RuffianZhong** [comment]
@zhengfuwang 
感谢反馈，已经修复，升级到 V1.1.4
