### ISSUE TITLE
RImageView内侧溢出情况还比较严重，大神有空解决下

### ISSUE THREAD

**Issue by wayneleo** [RuffianZhong/RWidgetHelper#54]
用的最新的1.1.7版本，这些机型及系统版本都发生了
![jixingjixitong](https://user-images.githubusercontent.com/5975005/70383641-2f7cd180-19ac-11ea-8478-728f9268f756.png)
![cuowuneirong](https://user-images.githubusercontent.com/5975005/70383644-34418580-19ac-11ea-85fe-bb1a6ac5235a.png)

**Comment by wayneleo** [comment]
详细日志
java.lang.OutOfMemoryError: Failed to allocate a 980112 byte allocation with 721037 free bytes and 704KB until OOM
    at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
    at android.graphics.Bitmap.nativeCreate(Native Method)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:812)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:756)
    at com.ruffian.library.widget.helper.RImageViewHelper.getBitmapFromDrawable(RImageViewHelper.java:290)
    at com.ruffian.library.widget.helper.RImageViewHelper.drawBitmap(RImageViewHelper.java:228)
    at com.ruffian.library.widget.helper.RImageViewHelper.onDraw(RImageViewHelper.java:201)
    at com.ruffian.library.widget.RImageView.onDraw(RImageView.java:31)
    at android.view.View.draw(View.java:15294)
    at android.view.View.updateDisplayListIfDirty(View.java:14230)
    at android.view.View.getDisplayList(View.java:14252)
    at android.view.View.draw(View.java:15022)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3563)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3356)
    at android.view.View.updateDisplayListIfDirty(View.java:14225)
    at android.view.View.getDisplayList(View.java:14252)
    at android.view.View.draw(View.java:15022)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3563)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3356)
    at android.view.View.draw(View.java:15297)
    at android.view.View.updateDisplayListIfDirty(View.java:14230)
    at android.view.View.getDisplayList(View.java:14252)
    at android.view.View.draw(View.java:15022)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3563)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3356)
    at android.view.View.draw(View.java:15297)
    at android.widget.FrameLayout.draw(FrameLayout.java:598)
    at android.view.View.updateDisplayListIfDirty(View.java:14230)
    at android.view.View.getDisplayList(View.java:14252)
    at android.view.View.draw(View.java:15022)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3563)
    at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:4820)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3356)
    at android.view.View.draw(View.java:15297)
    at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4219)
    at android.view.View.updateDisplayListIfDirty(View.java:14230)
    at android.view.View.getDisplayList(View.java:14252)
    at android.view.View.draw(View.java:15022)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3563)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3356)
    at android.view.View.updateDisplayListIfDirty(View.java:14225)
    at android.view.View.getDisplayList(View.java:14252)
    at android.view.View.draw(View.java:15022)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3563)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3356)
    at android.view.View.updateDisplayListIfDirty(View.java:14225)
    at android.view.View.getDisplayList(View.java:14252)
    at android.view.View.draw(View.java:15022)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3563)
    at com.scwang.smartrefresh.layout.SmartRefreshLayout.drawChild(SmartRefreshLayout.java:824)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3356)
    at android.view.View.draw(View.java:15297)
    at android.view.View.updateDisplayListIfDirty(View.java:14230)
    at android.view.View.getDisplayList(View.java:14252)
    at android.view.View.draw(View.java:15022)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3563)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3356)
    at android.view.View.draw(View.java:15297)
    at androidx.viewpager.widget.ViewPager.draw(ViewPager.java:2426)
    at android.view.View.updateDisplayListIfDirty(View.java:14230)
    at android.view.View.getDisplayList(View.java:14252)
    at android.view.View.draw(View.java:15022)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3563)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3356)
    at android.view.View.draw(View.java:15297)
    at android.view.View.updateDisplayListIfDirty(View.java:14230)
    at android.view.View.getDisplayList(View.java:14252)
    at android.view.View.draw(View.java:15022)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3563)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3356)
    at android.view.View.updateDisplayListIfDirty(View.java:14225)
    at android.view.View.getDisplayList(View.java:14252)
    at android.view.View.draw(View.java:15022)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3563)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3356)
    at android.view.View.updateDisplayListIfDirty(View.java:14225)
    at android.view.View.getDisplayList(View.java:14252)
    at android.view.View.draw(View.java:15022)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3563)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3356)
    at android.view.View.updateDisplayListIfDirty(View.java:14225)
    at android.view.View.getDisplayList(View.java:14252)
    at android.view.View.draw(View.java:15022)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3563)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3356)
    at android.view.View.updateDisplayListIfDirty(View.java:14225)
    at android.view.View.getDisplayList(View.java:14252)
    at android.view.View.draw(View.java:15022)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3563)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3356)
    at android.view.View.updateDisplayListIfDirty(View.java:14225)
    at android.view.View.getDisplayList(View.java:14252)
    at android.view.View.draw(View.java:15022)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3563)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3356)
    at android.view.View.draw(View.java:15297)
    at android.widget.FrameLayout.draw(FrameLayout.java:598)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2814)
    at android.view.View.updateDisplayListIfDirty(View.java:14230)
    at android.view.View.getDisplayList(View.java:14252)
    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:2601)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2417)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2018)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1092)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6050)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:805)
    at android.view.Choreographer.doCallbacks(Choreographer.java:618)
    at android.view.Choreographer.doFrame(Choreographer.java:588)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:791)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5418)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1037)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)

**Comment by RuffianZhong** [comment]
@wayneleo 
久等了，问题已经处理，请升级到 V1.1.8
