### ISSUE TITLE
1.1.8的bug，运行在安卓版本4.4.3的TV上出现如下错误

### ISSUE THREAD

**Issue by LouisKooAndroid** [RuffianZhong/RWidgetHelper#57]
![微信截图_20200108172810](https://user-images.githubusercontent.com/26615510/71966280-437e5200-323c-11ea-8a1b-67b8662d93c5.png)

实测1.1.7版本没有问题。

**Caused by**: android.view.InflateException: Binary XML file line #13: Error inflating class com.ruffian.library.widget.RTextView
        at android.view.LayoutInflater.createView(LayoutInflater.java:620)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.cxtc.tvboard.base.BaseMVPActivity.onCreate(BaseMVPActivity.java:36)
        at android.app.Activity.performCreate(Activity.java:5232)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
        at android.app.ActivityThread.access$800(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5008) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:851) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:673) 
        at dalvik.system.NativeStart.main(Native Method) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at android.view.LayoutInflater.createView(LayoutInflater.java:594)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
        at com.cxtc.tvboard.base.BaseMVPActivity.onCreate(BaseMVPActivity.java:36) 
        at android.app.Activity.performCreate(Activity.java:5232) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
        at android.app.ActivityThread.access$800(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5008) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:851) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:673) 
        at dalvik.system.NativeStart.main(Native Method) 
     **Caused by:** java.lang.NoClassDefFoundError: androidx.appcompat.content.res.AppCompatResources
        at com.ruffian.library.widget.helper.RTextViewHelper.initAttributeSet(RTextViewHelper.java:141)
        at com.ruffian.library.widget.helper.RTextViewHelper.<init>(RTextViewHelper.java:72)
        at com.ruffian.library.widget.RTextView.<init>(RTextView.java:26)
        at java.lang.reflect.Constructor.constructNative(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:594) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
        at com.cxtc.tvboard.base.BaseMVPActivity.onCreate(BaseMVPActivity.java:36) 
        at android.app.Activity.performCreate(Activity.java:5232) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)

**Comment by RuffianZhong** [comment]
@LouisKooAndroid 
V1.1.8 版本我对库进行androidX迁移，造成不能使用的原因是您的项目中没有我的库需要依赖的包。您可以使用以下方式解决：
1.在开发者项目的gradle中引入依赖包
```
    implementation 'androidx.appcompat:appcompat:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
```
2.升级到V1.1.9 （我修改了依赖关系为强制依赖，就是不管开发者有没有，此库都会引入依赖包）

**Comment by LouisKooAndroid** [comment]
大大牛逼！！万分感谢。

**Comment by LouisKooAndroid** [comment]
![微信截图_20200109091637](https://user-images.githubusercontent.com/26615510/72029392-c77a1d80-32c0-11ea-8ba2-fb5543bbb335.png)
大大，1.1.9版本，报了这个错误。

**Comment by RuffianZhong** [comment]
@LouisKooAndroid 
这个是您的项目未适配Androidx，而我的库适配了Androidx造成的问题，为了解决市面上对AndroidX适配情况的不一致，我处理了两个库（功能是一样的，区别在于是否适配AndroidX）
如果： 未支持 AndroidX
```
compile 'com.ruffian.library:RWidgetHelper:1.1.10'
```
如果：支持 AndroidX
```
compile 'com.ruffian.library:RWidgetHelper-AndroidX:0.0.1'
```

**Comment by LouisKooAndroid** [comment]
好嘞，现在可以了。
