### ISSUE TITLE
demo点击RTextView出现NullPointerException

### ISSUE THREAD

**Issue by lydlovezjr** [RuffianZhong/RWidgetHelper#6]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.ruffian.library.widget.helper.RTextViewHelper com.ruffian.library.widget.RTextView.getHelper()' on a null object reference
        at com.ruffian.library.demo.RTextViewActivity.onCreate(RTextViewActivity.java:35)
        at android.app.Activity.performCreate(Activity.java:6355)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2440)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2547) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:157) 
        at android.app.ActivityThread.main(ActivityThread.java:5603) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)

**Comment by RuffianZhong** [comment]
@lydlovezjr 
抱歉抱歉，之前测试时候的一段无用代码忘记删掉了。已经更新
