### ISSUE TITLE
RTextView设置icon 使用vectordrawable在6.0+机器上崩溃报Binary XML异常

### ISSUE THREAD

**Issue by tommy-siwer** [RuffianZhong/RWidgetHelper#76]
android.view.InflateException: Binary XML file line #28: Binary XML file line #46: Error inflating class <unknown>
        at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.kt:57)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
        at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.kt:48)
        at com.xuexiang.xpage.base.XPageFragment.inflateView(XPageFragment.java:603)
        at com.xuexiang.xpage.base.XPageFragment.onCreateView(XPageFragment.java:588)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)....
和FileNotFound ... ic_xxx_0...
经过验证，在6.0+系统上（华为，三星），RTextView 中使用png格式的可以，使用vector的崩溃。
在源码RTextViewHelper128行：
//icon
//Vector兼容处理
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.L) 
中将Build.VERSION_CODES.L改为7.0的"N",即兼容到7.0后，vectordrawable可正常显示，不过tint设置无效。
大佬给看看要不要调整下vector的适配逻辑~~
因为开发时没有考虑适配问题，结果所有图标都做成了svg格式的，现在要全部替换一遍的话感觉很蛋疼，自己重写覆盖源码毕竟不是理智的解决方案，所以大佬抽空给看下这个问题，项目也快上线了。
贴上别人的思路，“判断系统版本如果小于5.0，就用ContextCompat.getDrawable获取到Drawable实例，再setCompoundDrawablesWithIntrinsicBounds”
网上找到的答案都说是适配到5.0，但实际上我6.0+的机子上测试的时候，就出现崩溃了

**Comment by RuffianZhong** [comment]
@tommy-siwer 使用6.0.1模拟器，无法复现该问题，可否提供更完整一点的数据，或者使用最新版本再尝试一下
